//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: Java/src/test/java/harrycheung/map/shared/GateTest.java
//

#ifndef _HCMGateTest_H_
#define _HCMGateTest_H_

#include "J2ObjC_header.h"

@interface HCMGateTest : NSObject {
}

- (void)crossed;

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(HCMGateTest)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END

typedef HCMGateTest HarrycheungMapSharedGateTest;

J2OBJC_TYPE_LITERAL_HEADER(HCMGateTest)

#endif // _HCMGateTest_H_
