//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: Java/src/main/java/harrycheung/map/shared/GateType.java
//

#ifndef _HCMGateType_H_
#define _HCMGateType_H_

#include "J2ObjC_header.h"
#include "java/lang/Enum.h"

typedef NS_ENUM(NSUInteger, HCMGateType) {
  HCMGateType_START_FINISH = 0,
  HCMGateType_START = 1,
  HCMGateType_FINISH = 2,
  HCMGateType_SPLIT = 3,
  HCMGateType_TURN = 4,
};

@interface HCMGateTypeEnum : JavaLangEnum < NSCopying > {
}

- (instancetype)initWithNSString:(NSString *)__name
                         withInt:(jint)__ordinal;

+ (IOSObjectArray *)values;
FOUNDATION_EXPORT IOSObjectArray *HCMGateTypeEnum_values();

+ (HCMGateTypeEnum *)valueOfWithNSString:(NSString *)name;

FOUNDATION_EXPORT HCMGateTypeEnum *HCMGateTypeEnum_valueOfWithNSString_(NSString *name);
- (id)copyWithZone:(NSZone *)zone;

@end

FOUNDATION_EXPORT BOOL HCMGateTypeEnum_initialized;
J2OBJC_STATIC_INIT(HCMGateTypeEnum)

FOUNDATION_EXPORT HCMGateTypeEnum *HCMGateTypeEnum_values_[];

#define HCMGateTypeEnum_START_FINISH HCMGateTypeEnum_values_[HCMGateType_START_FINISH]
J2OBJC_ENUM_CONSTANT_GETTER(HCMGateTypeEnum, START_FINISH)

#define HCMGateTypeEnum_START HCMGateTypeEnum_values_[HCMGateType_START]
J2OBJC_ENUM_CONSTANT_GETTER(HCMGateTypeEnum, START)

#define HCMGateTypeEnum_FINISH HCMGateTypeEnum_values_[HCMGateType_FINISH]
J2OBJC_ENUM_CONSTANT_GETTER(HCMGateTypeEnum, FINISH)

#define HCMGateTypeEnum_SPLIT HCMGateTypeEnum_values_[HCMGateType_SPLIT]
J2OBJC_ENUM_CONSTANT_GETTER(HCMGateTypeEnum, SPLIT)

#define HCMGateTypeEnum_TURN HCMGateTypeEnum_values_[HCMGateType_TURN]
J2OBJC_ENUM_CONSTANT_GETTER(HCMGateTypeEnum, TURN)

typedef HCMGateTypeEnum HarrycheungMapSharedGateTypeEnum;

J2OBJC_TYPE_LITERAL_HEADER(HCMGateTypeEnum)

#endif // _HCMGateType_H_
