//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: Java/src/main/java/harrycheung/map/shared/Lap.java
//

#ifndef _HCMLap_H_
#define _HCMLap_H_

@class HCMPoint;
@class HCMSession;
@class HCMTrack;
@class IOSDoubleArray;
@protocol JavaUtilList;

#include "J2ObjC_header.h"

@interface HCMLap : NSObject {
 @public
  HCMTrack *track_;
  jdouble startTime_;
  jint lapNumber_;
  id<JavaUtilList> points_;
  jdouble duration_;
  jdouble distance_;
  jboolean valid_;
  IOSDoubleArray *splits_;
  jboolean outLap_;
}

- (instancetype)initWithHCMSession:(HCMSession *)session
                      withHCMTrack:(HCMTrack *)track
                        withDouble:(jdouble)startTime
                           withInt:(jint)lapNumber;

- (void)addWithHCMPoint:(HCMPoint *)point;

@end

J2OBJC_EMPTY_STATIC_INIT(HCMLap)

J2OBJC_FIELD_SETTER(HCMLap, track_, HCMTrack *)
J2OBJC_FIELD_SETTER(HCMLap, points_, id<JavaUtilList>)
J2OBJC_FIELD_SETTER(HCMLap, splits_, IOSDoubleArray *)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END

typedef HCMLap HarrycheungMapSharedLap;

J2OBJC_TYPE_LITERAL_HEADER(HCMLap)

#endif // _HCMLap_H_
