//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: Java/src/main/java/harrycheung/map/shared/Physics.java
//

#ifndef _HCMPhysics_H_
#define _HCMPhysics_H_

#include "J2ObjC_header.h"

@interface HCMPhysics : NSObject {
}

+ (jdouble)distanceWithDouble:(jdouble)velocity
                   withDouble:(jdouble)acceleration
                   withDouble:(jdouble)time;

+ (jdouble)timeWithDouble:(jdouble)distance
               withDouble:(jdouble)velocity
               withDouble:(jdouble)acceleration;

@end

J2OBJC_EMPTY_STATIC_INIT(HCMPhysics)

CF_EXTERN_C_BEGIN

FOUNDATION_EXPORT jdouble HCMPhysics_distanceWithDouble_withDouble_withDouble_(jdouble velocity, jdouble acceleration, jdouble time);

FOUNDATION_EXPORT jdouble HCMPhysics_timeWithDouble_withDouble_withDouble_(jdouble distance, jdouble velocity, jdouble acceleration);
CF_EXTERN_C_END

typedef HCMPhysics HarrycheungMapSharedPhysics;

J2OBJC_TYPE_LITERAL_HEADER(HCMPhysics)

#endif // _HCMPhysics_H_
