//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: Java/src/test/java/harrycheung/map/shared/PhysicsTest.java
//

#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "Physics.h"
#include "PhysicsTest.h"
#include "java/lang/Double.h"
#include "org/hamcrest/CoreMatchers.h"
#include "org/hamcrest/Matcher.h"
#include "org/junit/Assert.h"
#include "org/junit/Test.h"

@implementation HCMPhysicsTest

- (void)distance {
  OrgJunitAssert_assertThatWithId_withOrgHamcrestMatcher_(JavaLangDouble_valueOfWithDouble_(HCMPhysics_distanceWithDouble_withDouble_withDouble_(0, 0, 0)), OrgHamcrestCoreMatchers_isWithId_(JavaLangDouble_valueOfWithDouble_(0.0)));
  OrgJunitAssert_assertThatWithId_withOrgHamcrestMatcher_(JavaLangDouble_valueOfWithDouble_(HCMPhysics_distanceWithDouble_withDouble_withDouble_(1, 1, 1)), OrgHamcrestCoreMatchers_isWithId_(JavaLangDouble_valueOfWithDouble_(1.5)));
  OrgJunitAssert_assertThatWithId_withOrgHamcrestMatcher_(JavaLangDouble_valueOfWithDouble_(HCMPhysics_distanceWithDouble_withDouble_withDouble_(2, 2, 2)), OrgHamcrestCoreMatchers_isWithId_(JavaLangDouble_valueOfWithDouble_(8.0)));
  OrgJunitAssert_assertThatWithId_withOrgHamcrestMatcher_(JavaLangDouble_valueOfWithDouble_(HCMPhysics_distanceWithDouble_withDouble_withDouble_(3, 0, 3)), OrgHamcrestCoreMatchers_isWithId_(JavaLangDouble_valueOfWithDouble_(9.0)));
}

- (void)time {
  OrgJunitAssert_assertThatWithId_withOrgHamcrestMatcher_(JavaLangDouble_valueOfWithDouble_(HCMPhysics_timeWithDouble_withDouble_withDouble_(1.5, 1, 1)), OrgHamcrestCoreMatchers_isWithId_(JavaLangDouble_valueOfWithDouble_(1.0)));
  OrgJunitAssert_assertThatWithId_withOrgHamcrestMatcher_(JavaLangDouble_valueOfWithDouble_(HCMPhysics_timeWithDouble_withDouble_withDouble_(8.0, 2, 2)), OrgHamcrestCoreMatchers_isWithId_(JavaLangDouble_valueOfWithDouble_(2.0)));
  OrgJunitAssert_assertThatWithId_withOrgHamcrestMatcher_(JavaLangDouble_valueOfWithDouble_(HCMPhysics_timeWithDouble_withDouble_withDouble_(9.0, 3, 0)), OrgHamcrestCoreMatchers_isWithId_(JavaLangDouble_valueOfWithDouble_(3.0)));
}

- (instancetype)init {
  return [super init];
}

+ (IOSObjectArray *)__annotations_distance {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[[OrgJunitTest alloc] initWithExpected:OrgJunitTest_None_class_() withTimeout:0] autorelease] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_time {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[[OrgJunitTest alloc] initWithExpected:OrgJunitTest_None_class_() withTimeout:0] autorelease] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "distance", NULL, "V", 0x1, NULL },
    { "time", NULL, "V", 0x1, NULL },
    { "init", NULL, NULL, 0x1, NULL },
  };
  static const J2ObjcClassInfo _HCMPhysicsTest = { 1, "PhysicsTest", "harrycheung.map.shared", NULL, 0x1, 3, methods, 0, NULL, 0, NULL};
  return &_HCMPhysicsTest;
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(HCMPhysicsTest)
