//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: Java/src/test/java/harrycheung/map/shared/PointTest.java
//

#ifndef _HCMPointTest_H_
#define _HCMPointTest_H_

#include "J2ObjC_header.h"

@interface HCMPointTest : NSObject {
}

- (void)equals;

- (void)subtraction;

- (void)bearingTo;

- (void)destination;

- (void)distanceTo;

- (void)intersect;

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(HCMPointTest)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END

typedef HCMPointTest HarrycheungMapSharedPointTest;

J2OBJC_TYPE_LITERAL_HEADER(HCMPointTest)

#endif // _HCMPointTest_H_
