//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: Java/src/main/java/harrycheung/map/Session.java
//

#ifndef _HCMSession_H_
#define _HCMSession_H_

@class HCMTrack;
@protocol JavaUtilList;

#include "J2ObjC_header.h"

@interface HCMSession : NSObject {
 @public
  __weak HCMTrack *track_;
  jdouble startTime_;
  jdouble duration_;
  id<JavaUtilList> laps_;
}

- (instancetype)initWithHCMTrack:(HCMTrack *)track
                      withDouble:(jdouble)startTime;

- (void)tickWithDouble:(jdouble)currentTime;

@end

J2OBJC_EMPTY_STATIC_INIT(HCMSession)

J2OBJC_FIELD_SETTER(HCMSession, laps_, id<JavaUtilList>)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END

typedef HCMSession HarrycheungMapSession;

J2OBJC_TYPE_LITERAL_HEADER(HCMSession)

#endif // _HCMSession_H_
