//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: Java/src/test/java/harrycheung/map/SessionTest.java
//

#ifndef _HCMSessionTest_H_
#define _HCMSessionTest_H_

@class HCMTrack;

#include "J2ObjC_header.h"

@interface HCMSessionTest : NSObject {
}

- (void)setUp;

- (void)tearDown;

- (void)singleLapSession;

- (void)multiLapSession;

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(HCMSessionTest)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END

typedef HCMSessionTest HarrycheungMapSessionTest;

J2OBJC_TYPE_LITERAL_HEADER(HCMSessionTest)

#endif // _HCMSessionTest_H_
