//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: Java/src/test/java/harrycheung/map/shared/TrackTest.java
//

#ifndef _HCMTrackTest_H_
#define _HCMTrackTest_H_

#include "J2ObjC_header.h"

@interface HCMTrackTest : NSObject {
}

- (void)trackLoadFromJSON;

- (void)trackLoadFromJSONArray;

- (void)trackLoadFailOnId;

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(HCMTrackTest)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END

typedef HCMTrackTest HarrycheungMapSharedTrackTest;

J2OBJC_TYPE_LITERAL_HEADER(HCMTrackTest)

#endif // _HCMTrackTest_H_
