//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: Java/src/main/java/harrycheung/map/shared/GateType.java
//

#include "GateType.h"
#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "java/lang/IllegalArgumentException.h"

BOOL HCMGateTypeEnum_initialized = NO;

HCMGateTypeEnum *HCMGateTypeEnum_values_[5];

@implementation HCMGateTypeEnum

- (instancetype)initWithNSString:(NSString *)__name
                         withInt:(jint)__ordinal {
  return [super initWithNSString:__name withInt:__ordinal];
}

IOSObjectArray *HCMGateTypeEnum_values() {
  HCMGateTypeEnum_init();
  return [IOSObjectArray arrayWithObjects:HCMGateTypeEnum_values_ count:5 type:HCMGateTypeEnum_class_()];
}
+ (IOSObjectArray *)values {
  return HCMGateTypeEnum_values();
}

+ (HCMGateTypeEnum *)valueOfWithNSString:(NSString *)name {
  return HCMGateTypeEnum_valueOfWithNSString_(name);
}

HCMGateTypeEnum *HCMGateTypeEnum_valueOfWithNSString_(NSString *name) {
  HCMGateTypeEnum_init();
  for (int i = 0; i < 5; i++) {
    HCMGateTypeEnum *e = HCMGateTypeEnum_values_[i];
    if ([name isEqual:[e name]]) {
      return e;
    }
  }
  @throw [[[JavaLangIllegalArgumentException alloc] initWithNSString:name] autorelease];
  return nil;
}

- (id)copyWithZone:(NSZone *)zone {
  return [self retain];
}

+ (void)initialize {
  if (self == [HCMGateTypeEnum class]) {
    HCMGateTypeEnum_START_FINISH = [[HCMGateTypeEnum alloc] initWithNSString:@"START_FINISH" withInt:0];
    HCMGateTypeEnum_START = [[HCMGateTypeEnum alloc] initWithNSString:@"START" withInt:1];
    HCMGateTypeEnum_FINISH = [[HCMGateTypeEnum alloc] initWithNSString:@"FINISH" withInt:2];
    HCMGateTypeEnum_SPLIT = [[HCMGateTypeEnum alloc] initWithNSString:@"SPLIT" withInt:3];
    HCMGateTypeEnum_TURN = [[HCMGateTypeEnum alloc] initWithNSString:@"TURN" withInt:4];
    J2OBJC_SET_INITIALIZED(HCMGateTypeEnum)
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithNSString:withInt:", "init", NULL, 0x1, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "START_FINISH", "START_FINISH", 0x4019, "Lharrycheung.map.shared.GateType;", &HCMGateTypeEnum_START_FINISH,  },
    { "START", "START", 0x4019, "Lharrycheung.map.shared.GateType;", &HCMGateTypeEnum_START,  },
    { "FINISH", "FINISH", 0x4019, "Lharrycheung.map.shared.GateType;", &HCMGateTypeEnum_FINISH,  },
    { "SPLIT", "SPLIT", 0x4019, "Lharrycheung.map.shared.GateType;", &HCMGateTypeEnum_SPLIT,  },
    { "TURN", "TURN", 0x4019, "Lharrycheung.map.shared.GateType;", &HCMGateTypeEnum_TURN,  },
  };
  static const char *superclass_type_args[] = {"Lharrycheung.map.shared.GateType;"};
  static const J2ObjcClassInfo _HCMGateTypeEnum = { 1, "GateType", "harrycheung.map.shared", NULL, 0x4011, 1, methods, 5, fields, 1, superclass_type_args};
  return &_HCMGateTypeEnum;
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(HCMGateTypeEnum)
