//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: Java/src/test/java/harrycheung/map/shared/GateTest.java
//

#include "Gate.h"
#include "GateTest.h"
#include "GateType.h"
#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "Point.h"
#include "java/lang/Double.h"
#include "org/hamcrest/CoreMatchers.h"
#include "org/hamcrest/Matcher.h"
#include "org/junit/Assert.h"
#include "org/junit/Test.h"

@implementation HCMGateTest

- (void)crossed {
  HCMGate *gate = [[[HCMGate alloc] initWithHCMGateTypeEnum:HCMGateTypeEnum_get_START_FINISH() withInt:1 withDouble:37.452602 withDouble:-122.207069 withDouble:32] autorelease];
  HCMPoint *a = [[[HCMPoint alloc] initWithDouble:37.452414 withDouble:-122.207193 withDouble:14.210000038146973 withDouble:32.09501647949219 withDouble:0 withDouble:0 withDouble:1] autorelease];
  HCMPoint *b = [[[HCMPoint alloc] initWithDouble:37.452523 withDouble:-122.207107 withDouble:14.239999771118164 withDouble:32.09501647949219 withDouble:0 withDouble:0 withDouble:2] autorelease];
  b->lapDistance_ = 100.0;
  b->lapTime_ = 0.1;
  HCMPoint *c = [[[HCMPoint alloc] initWithDouble:37.45263 withDouble:-122.207023 withDouble:14.15999984741211 withDouble:32.09501647949219 withDouble:0 withDouble:0 withDouble:3] autorelease];
  OrgJunitAssert_assertNullWithId_([gate crossedWithHCMPoint:a withHCMPoint:b]);
  OrgJunitAssert_assertNullWithId_([gate crossedWithHCMPoint:c withHCMPoint:b]);
  HCMPoint *cross = [gate crossedWithHCMPoint:b withHCMPoint:c];
  OrgJunitAssert_assertTrueWithBoolean_(((HCMPoint *) nil_chk(cross))->generated_);
  OrgJunitAssert_assertThatWithId_withOrgHamcrestMatcher_(JavaLangDouble_valueOfWithDouble_([cross getLatitudeDegrees]), OrgHamcrestCoreMatchers_isWithId_(JavaLangDouble_valueOfWithDouble_(37.452593)));
  OrgJunitAssert_assertThatWithId_withOrgHamcrestMatcher_(JavaLangDouble_valueOfWithDouble_([cross getLongitudeDegrees]), OrgHamcrestCoreMatchers_isWithId_(JavaLangDouble_valueOfWithDouble_(-122.207052)));
  OrgJunitAssert_assertEqualsWithDouble_withDouble_withDouble_(14.18, cross->speed_, 0.01);
  OrgJunitAssert_assertEqualsWithDouble_withDouble_withDouble_(31.93, cross->bearing_, 0.01);
  OrgJunitAssert_assertEqualsWithDouble_withDouble_withDouble_(2.64915, cross->timestamp_, 0.00001);
  OrgJunitAssert_assertEqualsWithDouble_withDouble_withDouble_(100 + [b distanceToWithHCMPoint:cross], cross->lapDistance_, 0.01);
  OrgJunitAssert_assertEqualsWithDouble_withDouble_withDouble_(0.74915, cross->lapTime_, 0.00001);
  OrgJunitAssert_assertEqualsWithDouble_withDouble_withDouble_(0.64915, cross->splitTime_, 0.00001);
}

- (instancetype)init {
  return [super init];
}

+ (IOSObjectArray *)__annotations_crossed {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[[OrgJunitTest alloc] initWithExpected:OrgJunitTest_None_class_() withTimeout:0] autorelease] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "crossed", NULL, "V", 0x1, NULL },
    { "init", NULL, NULL, 0x1, NULL },
  };
  static const J2ObjcClassInfo _HCMGateTest = { 1, "GateTest", "harrycheung.map.shared", NULL, 0x11, 2, methods, 0, NULL, 0, NULL};
  return &_HCMGateTest;
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(HCMGateTest)
