//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: Java/src/main/java/harrycheung/map/shared/Lap.java
//

#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "Lap.h"
#include "Point.h"
#include "Session.h"
#include "Track.h"
#include "java/util/ArrayList.h"
#include "java/util/List.h"

@implementation HCMLap

- (instancetype)initWithHCMSession:(HCMSession *)session
                      withHCMTrack:(HCMTrack *)track
                        withDouble:(jdouble)startTime
                           withInt:(jint)lapNumber {
  if (self = [super init]) {
    HCMLap_set_track_(self, track);
    self->startTime_ = startTime;
    self->lapNumber_ = lapNumber;
    HCMLap_setAndConsume_points_(self, [[JavaUtilArrayList alloc] init]);
    self->duration_ = 0;
    self->distance_ = 0;
    self->valid_ = NO;
    HCMLap_setAndConsume_splits_(self, [IOSDoubleArray newArrayWithLength:[((HCMTrack *) nil_chk(track)) numSplits]]);
    self->outLap_ = (lapNumber == 0);
  }
  return self;
}

- (void)addWithHCMPoint:(HCMPoint *)point {
  duration_ = ((HCMPoint *) nil_chk(point))->lapTime_;
  distance_ = point->lapDistance_;
  [((id<JavaUtilList>) nil_chk(points_)) addWithId:point];
}

- (void)dealloc {
  RELEASE_(track_);
  RELEASE_(points_);
  RELEASE_(splits_);
  [super dealloc];
}

- (void)copyAllFieldsTo:(HCMLap *)other {
  [super copyAllFieldsTo:other];
  HCMLap_set_track_(other, track_);
  other->startTime_ = startTime_;
  other->lapNumber_ = lapNumber_;
  HCMLap_set_points_(other, points_);
  other->duration_ = duration_;
  other->distance_ = distance_;
  other->valid_ = valid_;
  HCMLap_set_splits_(other, splits_);
  other->outLap_ = outLap_;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithHCMSession:withHCMTrack:withDouble:withInt:", "Lap", NULL, 0x1, NULL },
    { "addWithHCMPoint:", "add", "V", 0x1, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "track_", NULL, 0x4, "Lharrycheung.map.shared.Track;", NULL,  },
    { "startTime_", NULL, 0x4, "D", NULL,  },
    { "lapNumber_", NULL, 0x4, "I", NULL,  },
    { "points_", NULL, 0x4, "Ljava.util.List;", NULL,  },
    { "duration_", NULL, 0x4, "D", NULL,  },
    { "distance_", NULL, 0x4, "D", NULL,  },
    { "valid_", NULL, 0x4, "Z", NULL,  },
    { "splits_", NULL, 0x4, "[D", NULL,  },
    { "outLap_", NULL, 0x4, "Z", NULL,  },
  };
  static const J2ObjcClassInfo _HCMLap = { 1, "Lap", "harrycheung.map.shared", NULL, 0x11, 2, methods, 9, fields, 0, NULL};
  return &_HCMLap;
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(HCMLap)
