//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: Java/src/test/java/harrycheung/map/shared/PhysicsTest.java
//

#ifndef _HCMPhysicsTest_H_
#define _HCMPhysicsTest_H_

#include "J2ObjC_header.h"

@interface HCMPhysicsTest : NSObject {
}

- (void)distance;

- (void)time;

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(HCMPhysicsTest)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END

typedef HCMPhysicsTest HarrycheungMapSharedPhysicsTest;

J2OBJC_TYPE_LITERAL_HEADER(HCMPhysicsTest)

#endif // _HCMPhysicsTest_H_
