//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: Java/src/test/java/harrycheung/map/shared/PointTest.java
//

#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "Point.h"
#include "PointTest.h"
#include "java/lang/Double.h"
#include "java/lang/Integer.h"
#include "java/lang/Math.h"
#include "org/hamcrest/CoreMatchers.h"
#include "org/hamcrest/Matcher.h"
#include "org/junit/Assert.h"
#include "org/junit/Test.h"

@implementation HCMPointTest

- (void)equals {
  HCMPoint *a = [[[HCMPoint alloc] initWithDouble:14 withDouble:14] autorelease];
  HCMPoint *b = [[[HCMPoint alloc] initWithDouble:14 withDouble:14] autorelease];
  HCMPoint *c = [[[HCMPoint alloc] initWithDouble:25 withDouble:25] autorelease];
  OrgJunitAssert_assertThatWithId_withOrgHamcrestMatcher_(a, OrgHamcrestCoreMatchers_equalToWithId_(b));
  OrgJunitAssert_assertThatWithId_withOrgHamcrestMatcher_(a, OrgHamcrestCoreMatchers_not__WithOrgHamcrestMatcher_(OrgHamcrestCoreMatchers_equalToWithId_(c)));
}

- (void)subtraction {
  HCMPoint *a = [[[HCMPoint alloc] initWithDouble:5 withDouble:5] autorelease];
  HCMPoint *b = [[[HCMPoint alloc] initWithDouble:10 withDouble:10] autorelease];
  HCMPoint *c = [b subtractWithHCMPoint:a];
  OrgJunitAssert_assertThatWithId_withOrgHamcrestMatcher_(JavaLangDouble_valueOfWithDouble_([((HCMPoint *) nil_chk(c)) getLatitudeDegrees]), OrgHamcrestCoreMatchers_isWithId_(JavaLangDouble_valueOfWithDouble_(5.0)));
  OrgJunitAssert_assertThatWithId_withOrgHamcrestMatcher_(JavaLangDouble_valueOfWithDouble_([c getLongitudeDegrees]), OrgHamcrestCoreMatchers_isWithId_(JavaLangDouble_valueOfWithDouble_(5.0)));
}

- (void)bearingTo {
  HCMPoint *a = [[[HCMPoint alloc] initWithDouble:5 withDouble:5] autorelease];
  HCMPoint *b = [[[HCMPoint alloc] initWithDouble:5 withDouble:10] autorelease];
  OrgJunitAssert_assertThatWithId_withOrgHamcrestMatcher_(JavaLangDouble_valueOfWithDouble_([a bearingToWithHCMPoint:b]), OrgHamcrestCoreMatchers_isWithId_(JavaLangDouble_valueOfWithDouble_(89.781973)));
  OrgJunitAssert_assertThatWithId_withOrgHamcrestMatcher_(JavaLangDouble_valueOfWithDouble_([a bearingToWithHCMPoint:b withBoolean:YES]), OrgHamcrestCoreMatchers_isWithId_(JavaLangDouble_valueOfWithDouble_(1.566991)));
}

- (void)destination {
  HCMPoint *a = [[[HCMPoint alloc] initWithDouble:37.452602 withDouble:-122.207069] autorelease];
  HCMPoint *d = [a destinationWithDouble:308 withDouble:50];
  OrgJunitAssert_assertThatWithId_withOrgHamcrestMatcher_(d, OrgHamcrestCoreMatchers_equalToWithId_([[[HCMPoint alloc] initWithDouble:37.452879 withDouble:-122.207515] autorelease]));
}

- (void)distanceTo {
  HCMPoint *a = [[[HCMPoint alloc] initWithDouble:50.06639 withDouble:-5.71472] autorelease];
  HCMPoint *b = [[[HCMPoint alloc] initWithDouble:58.64389 withDouble:-3.07000] autorelease];
  OrgJunitAssert_assertThatWithId_withOrgHamcrestMatcher_(JavaLangInteger_valueOfWithInt_((jint) JavaLangMath_roundWithDouble_([a distanceToWithHCMPoint:b])), OrgHamcrestCoreMatchers_isWithId_(JavaLangInteger_valueOfWithInt_(968854)));
}

- (void)intersect {
  HCMPoint *a = [[[HCMPoint alloc] initWithDouble:5 withDouble:5] autorelease];
  HCMPoint *b = [[[HCMPoint alloc] initWithDouble:15 withDouble:15] autorelease];
  HCMPoint *c = [[[HCMPoint alloc] initWithDouble:5 withDouble:15] autorelease];
  HCMPoint *d = [[[HCMPoint alloc] initWithDouble:15 withDouble:5] autorelease];
  HCMPoint *i = HCMPoint_intersectSimpleWithHCMPoint_withHCMPoint_withHCMPoint_withHCMPoint_(a, b, c, d);
  OrgJunitAssert_assertThatWithId_withOrgHamcrestMatcher_(JavaLangDouble_valueOfWithDouble_([((HCMPoint *) nil_chk(i)) getLatitudeDegrees]), OrgHamcrestCoreMatchers_isWithId_(JavaLangDouble_valueOfWithDouble_(10.0)));
  OrgJunitAssert_assertThatWithId_withOrgHamcrestMatcher_(JavaLangDouble_valueOfWithDouble_([i getLongitudeDegrees]), OrgHamcrestCoreMatchers_isWithId_(JavaLangDouble_valueOfWithDouble_(10.0)));
}

- (instancetype)init {
  return [super init];
}

+ (IOSObjectArray *)__annotations_equals {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[[OrgJunitTest alloc] initWithExpected:OrgJunitTest_None_class_() withTimeout:0] autorelease] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_subtraction {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[[OrgJunitTest alloc] initWithExpected:OrgJunitTest_None_class_() withTimeout:0] autorelease] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_bearingTo {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[[OrgJunitTest alloc] initWithExpected:OrgJunitTest_None_class_() withTimeout:0] autorelease] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_destination {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[[OrgJunitTest alloc] initWithExpected:OrgJunitTest_None_class_() withTimeout:0] autorelease] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_distanceTo {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[[OrgJunitTest alloc] initWithExpected:OrgJunitTest_None_class_() withTimeout:0] autorelease] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_intersect {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[[OrgJunitTest alloc] initWithExpected:OrgJunitTest_None_class_() withTimeout:0] autorelease] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "equals", NULL, "V", 0x1, NULL },
    { "subtraction", NULL, "V", 0x1, NULL },
    { "bearingTo", NULL, "V", 0x1, NULL },
    { "destination", NULL, "V", 0x1, NULL },
    { "distanceTo", NULL, "V", 0x1, NULL },
    { "intersect", NULL, "V", 0x1, NULL },
    { "init", NULL, NULL, 0x1, NULL },
  };
  static const J2ObjcClassInfo _HCMPointTest = { 1, "PointTest", "harrycheung.map.shared", NULL, 0x11, 7, methods, 0, NULL, 0, NULL};
  return &_HCMPointTest;
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(HCMPointTest)
