//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: Java/src/main/java/harrycheung/map/shared/SessionManager.java
//

#ifndef _HCMSessionManager_H_
#define _HCMSessionManager_H_

@class HCMGate;
@class HCMLap;
@class HCMPoint;
@class HCMSession;
@class HCMTrack;
@class IOSDoubleArray;

#include "J2ObjC_header.h"

@interface HCMSessionManager : NSObject {
 @public
  HCMSession *session_;
  HCMLap *currentLap_;
  HCMLap *bestLap_;
  HCMTrack *track_;
}

+ (HCMSessionManager *)getInstance;

- (void)startSessionWithHCMTrack:(HCMTrack *)track;

- (void)endSession;

- (void)gpsWithDouble:(jdouble)latitude
           withDouble:(jdouble)longitude
           withDouble:(jdouble)speed
           withDouble:(jdouble)bearing
           withDouble:(jdouble)horizontalAccuracy
           withDouble:(jdouble)verticalAccuracy
           withDouble:(jdouble)timestamp;

@end

FOUNDATION_EXPORT BOOL HCMSessionManager_initialized;
J2OBJC_STATIC_INIT(HCMSessionManager)

J2OBJC_FIELD_SETTER(HCMSessionManager, session_, HCMSession *)
J2OBJC_FIELD_SETTER(HCMSessionManager, currentLap_, HCMLap *)
J2OBJC_FIELD_SETTER(HCMSessionManager, bestLap_, HCMLap *)
J2OBJC_FIELD_SETTER(HCMSessionManager, track_, HCMTrack *)

CF_EXTERN_C_BEGIN

FOUNDATION_EXPORT HCMSessionManager *HCMSessionManager_getInstance();

FOUNDATION_EXPORT HCMSessionManager *HCMSessionManager_instance_;
J2OBJC_STATIC_FIELD_GETTER(HCMSessionManager, instance_, HCMSessionManager *)
J2OBJC_STATIC_FIELD_SETTER(HCMSessionManager, instance_, HCMSessionManager *)
CF_EXTERN_C_END

typedef HCMSessionManager HarrycheungMapSharedSessionManager;

J2OBJC_TYPE_LITERAL_HEADER(HCMSessionManager)

#endif // _HCMSessionManager_H_
