//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: Java/src/main/java/harrycheung/map/shared/Session.java
//

#include "J2ObjC_source.h"
#include "Session.h"
#include "Track.h"
#include "java/util/ArrayList.h"
#include "java/util/List.h"

@implementation HCMSession

- (instancetype)initWithHCMTrack:(HCMTrack *)track
                      withDouble:(jdouble)startTime {
  if (self = [super init]) {
    duration_ = 0;
    HCMSession_setAndConsume_laps_(self, [[JavaUtilArrayList alloc] init]);
    HCMSession_set_track_(self, track);
    self->startTime_ = startTime;
  }
  return self;
}

- (void)tickWithDouble:(jdouble)currentTime {
  duration_ = currentTime - startTime_;
}

- (void)dealloc {
  RELEASE_(track_);
  RELEASE_(laps_);
  [super dealloc];
}

- (void)copyAllFieldsTo:(HCMSession *)other {
  [super copyAllFieldsTo:other];
  HCMSession_set_track_(other, track_);
  other->startTime_ = startTime_;
  other->duration_ = duration_;
  HCMSession_set_laps_(other, laps_);
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithHCMTrack:withDouble:", "Session", NULL, 0x1, NULL },
    { "tickWithDouble:", "tick", "V", 0x1, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "track_", NULL, 0x4, "Lharrycheung.map.shared.Track;", NULL,  },
    { "startTime_", NULL, 0x4, "D", NULL,  },
    { "duration_", NULL, 0x4, "D", NULL,  },
    { "laps_", NULL, 0x4, "Ljava.util.List;", NULL,  },
  };
  static const J2ObjcClassInfo _HCMSession = { 1, "Session", "harrycheung.map.shared", NULL, 0x11, 2, methods, 4, fields, 0, NULL};
  return &_HCMSession;
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(HCMSession)
