/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class harrycheung_map_cppandroid_HCMSessionManager */

#ifndef _Included_harrycheung_map_cppandroid_HCMSessionManager
#define _Included_harrycheung_map_cppandroid_HCMSessionManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     harrycheung_map_cppandroid_HCMSessionManager
 * Method:    start
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_harrycheung_map_cppandroid_HCMSessionManager_start
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     harrycheung_map_cppandroid_HCMSessionManager
 * Method:    gps
 * Signature: (DDDDD)V
 */
JNIEXPORT void JNICALL Java_harrycheung_map_cppandroid_HCMSessionManager_gps
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     harrycheung_map_cppandroid_HCMSessionManager
 * Method:    end
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_harrycheung_map_cppandroid_HCMSessionManager_end
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
