/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class harrycheung_map_cppandroid_HCMGate */

#ifndef _Included_harrycheung_map_cppandroid_HCMGate
#define _Included_harrycheung_map_cppandroid_HCMGate
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     harrycheung_map_cppandroid_HCMGate
 * Method:    loadGate
 * Signature: (IIDDD)J
 */
JNIEXPORT jlong JNICALL Java_harrycheung_map_cppandroid_HCMGate_loadGate
  (JNIEnv *, jclass, jint, jint, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
