/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class harrycheung_map_cppandroid_HCMTrack */

#ifndef _Included_harrycheung_map_cppandroid_HCMTrack
#define _Included_harrycheung_map_cppandroid_HCMTrack
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     harrycheung_map_cppandroid_HCMTrack
 * Method:    loadTrack
 * Signature: ([JJ)J
 */
JNIEXPORT jlong JNICALL Java_harrycheung_map_cppandroid_HCMTrack_loadTrack
  (JNIEnv *, jclass, jlongArray, jlong);

#ifdef __cplusplus
}
#endif
#endif
